### ISSUE TITLE
Equation rendering getting wrong

### ISSUE THREAD

**Issue by jatin-47** [hrushikeshrv/mjxgui#25]
![image](https://github.com/hrushikeshrv/mjxgui/assets/67009939/fd9fcd1d-b1a8-4a42-b301-9dc3f49d52d1)
![image](https://github.com/hrushikeshrv/mjxgui/assets/67009939/b6898830-9887-4710-b64d-ea14e804f3b6)

If I am typing an open "{" bracket and not closing it, then MathJax is not rendering it.

**Comment by hrushikeshrv** [comment]
Hi @jatin-47, thanks for the report!
You're right, `{` is a special character in LaTeX, so MathJax thinks it is an incomplete block. To fix this, we will have to change `Cursor.keyPress()` to check if the pressed key is `{` or `}`, and manually insert `"\{"` as a `TextComponent` whenever `{` is pressed and `"\}"` when `}` is pressed, similar to how it is done on [this line](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/cursor.js#L139). We will also need to remove `{` and `}` from the `characters` variable on [this line](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/cursor.js#L4).

Let me know if you would be able to work on this issue, otherwise I can take it up.

Thanks again 👍🏻

**Comment by jatin-47** [comment]
Yeah, I would be able to work on this issue.

**Comment by hrushikeshrv** [comment]
No, you just have to make changes in the `cursor.js` file. You can then use Grunt.js to automatically generate the other 3 files (see [grunt docs](https://gruntjs.com/getting-started)). The gruntfile is already configured in the project root, you will just need to install and run grunt. 

Thanks for volunteering, I'll assign this to you!

**Comment by jatin-47** [comment]
>manually insert `"\{"` as a `TextComponent` whenever `{` is pressed 

Should I insert it as a `MJXGUISymbol`?
We can treat this as a latex with not arguments and then we can handle the other cases which are not yet handled like :
![image](https://github.com/hrushikeshrv/mjxgui/assets/67009939/7d9e95cd-84f1-4b8c-90c2-1e5cf8e1546b)
![image](https://github.com/hrushikeshrv/mjxgui/assets/67009939/def5e23f-7fff-4d2b-a0e8-60cd591c4b16)

**Comment by hrushikeshrv** [comment]
Yeah, that should work. We should then handle all of the symbols you have mentioned above in the same patch 👍🏻

**Comment by jatin-47** [comment]
How should I do changes in `editor.html` as the whole HTML content in that is injected using `ui.js`. Is there a way to build `ui.js` from `editor.html`?

**Comment by hrushikeshrv** [comment]
I don't think you need to edit the HTML for this issue. You will just need to edit the `cursor.js` file, particularly the `keyPress()` method on the `Cursor` class. You will need to do something similar to what is done on [this line](https://github.com/hrushikeshrv/mjxgui/blob/1c61ba2f85fb436d95162ee0b9013fe8b3601a4f/src/modules/cursor.js#L139).

**Comment by jatin-47** [comment]
Yeah, I have done that but to add the floor, ceil and angle symbols, I have to add them to the UI, for now, I have done that manually but I guess we should do something regarding this to make changes in `editor.html` efficiently.

**Comment by hrushikeshrv** [comment]
Oh, I think we should leave out those symbols for the sake of this patch. For now, just consider adding support for the symbols you mentioned above except floor, ceil, angle brackets, and `|`. We should create a separate issue for adding support for those symbols, since that will require editing the HTML and other files.
