### ISSUE TITLE
Provide Latex as input for further edit

### ISSUE THREAD

**Issue by ronaksv** [hrushikeshrv/mjxgui#56]
This is an excellent tool 🔥 
Well, I was searching for an option to provide my previously generated latex as an input to this editor so that it can render the latex and then I can edit for enhancing my latex, but I could not find it.

For eg. in your 'example 5' text input was converted into an equation editor. Once we enter an equation, the button changes to "edit". When we click on edit, it shows up the UI but with blank input. I have to enter the entire equation again and then make my changes. Instead is there an option where I click on edit, it takes up the already generated latex as input and shows it on the editor?
 Let me know if its possible

**Comment by hrushikeshrv** [comment]
Hi @ronaksv, thanks for this suggestion. This would be a good behavior to have. Implementing this will take some planning, but this feature certainly can be added. I'll take this up 👍🏻

**Comment by ronaksv** [comment]
Awesome that you are taking it up. How are you planning to implement this? 
What I can think of is: scan the input latex, whenever each component starts, add it to a stack and keep on creating blocks and components by popping it out of stack?

**Comment by hrushikeshrv** [comment]
Yes, that would be a more generalized solution which would work as well. In my opinion, we can add that in addition to the persistence I'm adding in #57 - both would be nice to have. Maybe we could add a method named `fromLatex()` or similar with that functionality. However, I don't have the time required to commit to that feature right now.

If you're able to (and willing to) dedicate the time to implementing it, I would be more than happy to review your PR. Otherwise, I can take that up as well.

**Comment by ronaksv** [comment]
I would love to contribute. I am a bit tied up this week, probably I can take it up next week. Let me know if you start working before that
